# Generated by Django 4.1 on 2022-10-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrv', '0002_userwatch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userwatch',
            options={'verbose_name_plural': 'watches'},
        ),
        migrations.RemoveField(
            model_name='userwatch',
            name='watch_user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='watch',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
